# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lash < Formula
  desc "Commandline tool to manage PlatformNOW Landscape IDP."
  homepage "https://github.com/platformnow/lash"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/platformnow/lash/releases/download/v0.0.1/lash_0.0.1_darwin_arm64.tar.gz"
      sha256 "092f1577919315a2c78949abef90f174d4d39b50293fcd72ee5a90e9f2110db1"

      def install
        bin.install "lash"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/platformnow/lash/releases/download/v0.0.1/lash_0.0.1_darwin_amd64.tar.gz"
      sha256 "a431903d445d9ce2effc1c8bd4805762d5bf89d2bfb94ea8950f0b5cac2c8ee1"

      def install
        bin.install "lash"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/platformnow/lash/releases/download/v0.0.1/lash_0.0.1_linux_amd64.tar.gz"
      sha256 "93d683589e7ebe1b51dc08e596cac3d7d33574cba156e2992392d350b7c98699"

      def install
        bin.install "lash"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/platformnow/lash/releases/download/v0.0.1/lash_0.0.1_linux_arm64.tar.gz"
      sha256 "e81c97a29d77837c3306f7ae0bb6895db0016a585dcc8b4e1cdd8847bfdd36e1"

      def install
        bin.install "lash"
      end
    end
  end
end
